// قائمة بالحقول المسموح بها في systemSettings validator
export const ALLOWED_SETTINGS_FIELDS = [
  'siteName',
  'siteNameAr', 
  'siteDescription',
  'siteDescriptionAr',
  'contactEmail',
  'contactPhone',
  'supportEmail',
  'supportPhone',
  'address',
  'addressAr',
  'logoUrl',
  'faviconUrl',
  'primaryColor',
  'secondaryColor',
  'currency',
  'currencySymbol',
  'language',
  'timezone',
  'maintenanceMode',
  'allowRegistration',
  'emailVerificationRequired',
  'phoneVerificationRequired',
  'requirePhoneVerification',
  'commissionRate',
  'defaultCommissionRate',
  'captainCommissionRate',
  'storeApprovalRequired',
  'captainApprovalRequired',
  'autoAcceptOrders',
  'orderTimeoutMinutes',
  'maxProductsPerStore',
  'enableReviews',
  'enableRatings',
  'enableNotifications',
  'enableEmailNotifications',
  'enableSMSNotifications',
  'enablePushNotifications',
  'minOrderAmount',
  'freeDeliveryThreshold',
  'deliveryFee',
  'taxRate',
  'walletPhone',
  'socialLinks',
  'paymentMethods',
  'deliveryOptions'
] as const;

export type AllowedSettingsField = typeof ALLOWED_SETTINGS_FIELDS[number];
